---
controller_templates:
  - name: "F5 -0- AWS -Gather specific facts"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 0_bigip_facts.yml
    credentials:
      - Daily Demo F5 Network

  - name: "F5 -1- AWS -Import certificate and key"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 1_bigip_cert_key_import.yml
    credentials:
      - Daily Demo F5 Network
      - Daily Demo F5
      - F5 Vault
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-1-AWS-Import_cert_and_key.json') | regex_replace('\\n', '') }}"

  - name: "F5 -2- AWS -Create custom clientssl"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 2_client_ssl_profile.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-2-AWS-Create_custom_clientssl.json') | regex_replace('\\n', '') }}"

  - name: "F5 -2- AWS -Add custom HTTP profile"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 2_create_http_profile.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-2-AWS-Add_custom_HTTP_profile.json') | regex_replace('\\n', '') }}"


  - name: "F5 -2- AWS -Create custom TCP profile"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 2_create_tcp_profile.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-2-AWS-Create_custom_TCP_profile.json') | regex_replace('\\n', '') }}"

  - name: "F5 -2- AWS -Disable pool member"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: disable_pool_member.yml
    credentials:
      - Daily Demo F5 Network

  - name: "F5 -3- AWS -Add pool and members"
    description: "will add ec2 pool members with tag ml_demo"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 3_bigip_pool_and_members.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-3-AWS-Add_pool_and_members.json') | regex_replace('\\n', '') }}"

  - name: "F5 -4- AWS -Create VIP"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 4_bigip_virtual_server.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-4-AWS-Create_VIP.json') | regex_replace('\\n', '') }}"

  - name: "F5 -6- AWS -Delete pool"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 6_bigip_delete_pool.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-6-AWS-Delete_pool.json') | regex_replace('\\n', '') }}"

  - name: F5 -6- AWS -Delete custom TCP profile
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 2_create_tcp_profile.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-6-AWS-Delete_custom_TCP_profile.json') | regex_replace('\\n', '') }}"

  - name: "F5 -6- AWS -Delete certificate and key"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 6_delete_bigip_cert_key.yml
    credentials:
      - Daily Demo F5 Network
      - F5 Vault
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-6-AWS-Delete_certificate_and_key.json') | regex_replace('\\n', '') }}"

  - name: "F5 -6- AWS -Delete VIP"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 4_bigip_virtual_server.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-6-AWS-Delete_VIP.json') | regex_replace('\\n', '') }}"

  - name: "F5 -6- AWS -Delete custom clientssl"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 2_client_ssl_profile.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-6-AWS-Delete_custom_clientssl.json') | regex_replace('\\n', '') }}"

  - name: F5 -6- AWS -Delete custom HTTP profile
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: 2_create_http_profile.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-6-AWS-Delete_custom_HTTP_profile.json') | regex_replace('\\n', '') }}"

  - name: F5 -7- AWS -Change admin password
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: mlowcher_F5_examples
    playbook: change_admin_passwd.yml
    credentials:
      - Daily Demo F5 Network
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/F5-7-Change_admin_password.json') | regex_replace('\\n', '') }}"

  - name: "Daily Demo F5 Create/Remove"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: aap.dailydemo.F5
    playbook: playbooks/main.yml
    ask_tags_on_launch: true
    job_tags: create,remove
    credentials:
      - Daily Demo F5
      - "{{ my_aws_credential }}"
      - "{{ my_aap_credential }}"
    extra_vars:
      my_remote_ssh_pub_key: "{{ my_remote_ssh_pub_key }}"
    survey_enabled: true
    survey: "{{ lookup('template', 'template_surveys/basic_survey.json') | regex_replace('\\n', '') }}"

  - name: "Daily Demo F5 website"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: aap.dailydemo.F5
    playbook: playbooks/website_setup.yml
    credentials:
      - "{{ my_aws_machine_credential }}"

  - name: "Day 2 - connection test"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: aap.dailydemo.F5
    playbook: playbooks/connection.yml
    credentials:
      - "{{ my_aws_machine_credential }}"

  - name: "Day 2 - lb pool check"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: aap.dailydemo.F5
    playbook: playbooks/day2_lb_pool_check.yml
    credentials:
      - Network F5

  - name: "Day 2 - Linux File Checker"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: aap.dailydemo.F5
    playbook: playbooks/day2filecheck.yml
    credentials:
      - "{{ my_aws_machine_credential }}"

  - name: "Day 2 - Linux Patching"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: F5_ee
    project: aap.dailydemo.F5
    playbook: playbooks/day2patching.yml
    credentials:
      - Network F5
      - "{{ my_aws_machine_credential }}"

  - name: "Day 2 - Webservice check"
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: aap.dailydemo.F5
    playbook: playbooks/day2appcheck.yml
    credentials:
      - "{{ my_aws_machine_credential }}"