---
controller_credentials:
  - name: Daily Demo F5
    description: ssh key based authentication
    organization: "{{ my_organization }}"
    credential_type: Machine
    inputs:
      username: admin
      ssh_key_data: "{{ ssh_priv_key }}"

  - name: Network F5
    description: Used for the automated patching playbook
    organization: "{{ my_organization }}"
    credential_type: "Network F5"
    inputs:
      username: admin
      password: "{{ admin_password }}"

  - name: Daily Demo F5 Network
    description: Userid and password
    organization: "{{ my_organization }}"
    credential_type: Network
    inputs:
      username: admin
      password: "{{ admin_password }}"

  - name: quay.io
    organization: "{{ my_organization }}"
    credential_type: Container Registry
    inputs:
      password: "{{ quay_passwd }}"
      username: "{{ quay_username }}"
      host: quay.io
      verify_ssl: true

  - name: F5 Vault
    description: F5 Vault password team default password used
    organization: "{{ my_organization }}"
    credential_type: Vault
    inputs:
      vault_password: "{{ default_passwd }}"
