---
controller_credential_types:
- name: Network F5
  description: This is used by the patching demo
  inputs:
    fields:
      - id: username
        type: string
        label: Username
      - id: password
        type: string
        label: Password
        secret: true
    required:
      - username
      - password
  injectors:
    env:
      password: '{{ password }}'
      username: '{{ username }}'
